# this file uses prebuilt image in dockerhub
services:
  jekyll:
    # image: georgegca/multi-language-al-folio:v1.11.0
    image: georgegca/multi-language-al-folio:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
